const dialog=document.querySelector('#ticketDialog');const toast=document.querySelector('#toast');const ticketList=document.querySelector('#ticketList');const openCount=document.querySelector('#openCount');const ticketBadge=document.querySelector('#ticketBadge');
const savedTickets=JSON.parse(localStorage.getItem('conectaposTickets')||'[]');
function ticketHtml(ticket){return `<span class="ticket-type technical">▤</span><div class="ticket-main"><div class="ticket-title"><strong>${ticket.subject.replace(/[<>]/g,'')}</strong><span class="pill open">Aberto</span></div><p>Protocolo #CP-2026-${ticket.number} · ${ticket.type}</p><div class="sla"><span><i style="width:10%"></i></span><small>SLA: 24h restantes</small></div></div><div class="ticket-side"><small>Agora</small><b>›</b></div>`}
function updateCounts(){const total=3+savedTickets.length;openCount.textContent=total;ticketBadge.textContent=total}
savedTickets.slice().reverse().forEach(ticket=>{const item=document.createElement('article');item.className='ticket';item.dataset.status='Aberto';item.innerHTML=ticketHtml(ticket);ticketList.prepend(item)});updateCounts();
document.querySelector('#openTicket').addEventListener('click',()=>dialog.showModal());document.querySelector('.close').addEventListener('click',()=>dialog.close());document.querySelector('.close-action').addEventListener('click',()=>dialog.close());
function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3200)}
document.querySelector('#ticketForm').addEventListener('submit',e=>{e.preventDefault();const subject=document.querySelector('#ticketSubject').value.trim();const type=document.querySelector('#ticketType').value;if(!subject||!type){showToast('Preencha os campos obrigatórios.');return}const number=Math.floor(1000+Math.random()*8999);const ticket={subject,type,number};const item=document.createElement('article');item.className='ticket';item.dataset.status='Aberto';item.innerHTML=ticketHtml(ticket);ticketList.prepend(item);savedTickets.push(ticket);localStorage.setItem('conectaposTickets',JSON.stringify(savedTickets));updateCounts();dialog.close();e.target.reset();showToast(`Chamado aberto! Protocolo #CP-2026-${number}`)});
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));button.classList.add('active');document.querySelectorAll('.ticket').forEach(ticket=>{ticket.style.display=button.dataset.filter==='Todos'||ticket.dataset.status===button.dataset.filter?'grid':'none'})}));
const chat=document.querySelector('#chatPanel');document.querySelector('#chatButton').addEventListener('click',()=>{chat.classList.add('open');chat.setAttribute('aria-hidden','false')});document.querySelector('#closeChat').addEventListener('click',()=>{chat.classList.remove('open');chat.setAttribute('aria-hidden','true')});document.querySelectorAll('.suggestions button').forEach(b=>b.addEventListener('click',()=>showToast('Opção selecionada: '+b.textContent)));document.querySelectorAll('[data-help]').forEach(b=>b.addEventListener('click',()=>showToast('Conteúdo de ajuda aberto.')));document.querySelector('.see-all').addEventListener('click',()=>showToast('Você já está vendo os chamados mais recentes.'));
